vvp:

  ### Configure VVP to use a local SQLite Database
  persistence:
    type: local

  ### Configure Minio for Universal Blob Storage
  blobStorage:
    baseUri: s3://vvp
    s3:
      endpoint: http://minio.vvp.svc:9000

  ### Configure some global defaults for Deployments in this instance of Ververica Platform
  globalDeploymentDefaults: |
    spec:
      state: RUNNING
      template:
        spec:
          resources:
            jobmanager:
              cpu: 0.5
              memory: 1G
            taskmanager:
              cpu: 0.5
              memory: 1G
          flinkConfiguration:
            state.backend: filesystem
            taskmanager.memory.managed.fraction: 0.0 # no managed memory needed for filesystem statebackend
            high-availability: vvp-kubernetes
            metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
          kubernetes:
            pods:
              annotations:
                prometheus.io/port: '9249'
                prometheus.io/scrape: 'true'

  ui:
    linkTemplates:
      metrics: http://localhost:3000/d/77Nra5XZz/flink-dashboard?var-deploymentId=<%= deploymentId %>

blobStorageCredentials:
  s3:
    accessKeyId: admin
    secretAccessKey: password

### Allow Ververica Platform to manage Apache Flink deployments in "vvp-jobs" namespace
rbac:
  additionalNamespaces:
  - vvp-jobs
