# Disable authentication
grafana.ini:
  auth:
    disable_login_form: true
  auth.anonymous:
    enabled: true
    org_role: Admin

# Configure the Prometheus datasource
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      isDefault: true
      url: http://prometheus-server.vvp.svc
    - name: Elasticsearch
      type: elasticsearch
      access: proxy
      database: "github_stats*"
      url: http://elasticsearch-master-headless:9200
      jsonData:
        timeField: "windowStart"
        interval: null
        esVersion: 70


# Configure Grafana to load dashboards from the given directory
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: default
      orgId: 1
      folder: ''
      type: file
      disableDeletion: true
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

# Include a sample Flink dashboard with:
#   --set-file dashboards.default.flink-dashboard.json=grafana-dashboard.json
#   --set-file dashboards.default.github_stats-dashboard.json=github-stats-grafana-dashboard.json
