### Configure Minio for Universal Blob Storage
vvp:
  blobStorage:
    baseUri: s3://vvp

    s3:
      endpoint: http://minio.minio.svc.cluster.local:9000

blobStorageCredentials:
  s3:
    accessKeyId: admin
    secretAccessKey: password

### Allow Ververica Platform to manage Apache Flink deployments in "vvp-jobs" namespace
rbac:
  additionalNamespaces:
    - vvp-jobs